### ISSUE TITLE
Customizable keyboard shortcuts

### ISSUE THREAD

**Issue by azizLIGHT** [behnamazimi/youtube-subtitle-delay#1]
Please allow the use of other keys besides A and D to increase/decrease subtitle delay. Currently the extension does not show up in chrome://extensions/shortcuts to allow for it.

**Comment by behnamazimi** [comment]
Hey @azizLIGHT, I see what you mean but I thought it would be good for the majority of users to remove the complexity of setting shortcuts. Consider the "M" key on YouTube which mutes the volume or the "C" which toggles the subtitles.
