### ISSUE TITLE
Sync delayed subtitles from live streams

### ISSUE THREAD

**Issue by azizLIGHT** [behnamazimi/youtube-subtitle-delay#2]
Sometimes live streams can have very delayed subtitles. If one decides to watch a live stream delayed by some seconds, it could be possible to sync the subtitles to video manually with negative subtitle delay. 

For example, if a live stream's captioning is delayed by 2000 ms compared to the audio, one could watch the live stream delayed by 2000 ms and delay the subtitles by -2000 ms (play subtitles at 2000 ms faster than live stream), then one could have synced audio with synced subtitles. It would require getting live subtitles ahead of the delayed video stream.

Please consider if such a thing could be added. Thanks

**Comment by behnamazimi** [comment]
Hey @azizLIGHT,
Technically it is not possible to do this with an extension. The extension just tracks already streamed contents (both video and audio are together) and does some manipulations on client-side.

**Comment by azizLIGHT** [comment]
Thank you. The idea is out of scope then!
