### ISSUE TITLE
support Firefox, linux or android or not

### ISSUE THREAD

**Issue by passerbyo** [behnamazimi/youtube-subtitle-delay#3]

**Comment by behnamazimi** [comment]
You can install it on any chromium-based browser that supports extensions, no matter what the operating system is. Firefox is not supported yet. @passerbyo

**Comment by upgradepa** [comment]
https://download-chromium.appspot.com/

i can not find options to intstall this extension on chromium device

**Comment by upgradepa** [comment]
#4
