### ISSUE TITLE
support android device

### ISSUE THREAD

**Issue by upgradepa** [behnamazimi/youtube-subtitle-delay#4]
https://download-chromium.appspot.com/

i can not find options to intstall this extension on chromium device

**Comment by upgradepa** [comment]
#3

**Comment by behnamazimi** [comment]
@upgradepa Only a few android browsers allow you to install extensions. I don't know which one you are using. this extension could be installed on the majority of desktop browsers, I tested on well-known browsers on desktop, but I'm not sure about android devices.
