### ISSUE TITLE
The subtitle is not placed in the middle of the video frame

### ISSUE THREAD

**Issue by thou05** [behnamazimi/youtube-subtitle-delay#6]
Hello, thank you for your extension. It has been very helpful, but I've come across a small issue.

The subtitle is not placed in the middle of the video frame. It would be nice if you could take a look at it.

Here is a screenshot:
![image](https://github.com/behnamazimi/youtube-subtitle-delay/assets/139248123/2dabc80a-c04a-4d60-bff3-e73b6a8c0b25)

**Comment by behnamazimi** [comment]
Hey @thou05 , thanks for reporting. Will check it as soon as I can.

**Comment by behnamazimi** [comment]
Got it fixed and send the extension to be published. v1.4. Thanks again for reporting.
